### ISSUE TITLE
방장 1인일때 해야할것 ( 본문참고 )

### ISSUE THREAD

**Issue by hgn1027** [jyshoon/WordGuessApp-Android#67]
1. 혼자 게임 진행 불가하게 조정하기
2. 방 나가기 할 때, 방장도 나가게 조정. + 방 삭제

**Comment by jyshoon** [comment]
1. 혼자 게임 진행 불가하게 조정하기
  --> 해결

2. 방장이 방나가기 버튼 눌렀을 떄
  - 2인 이상 있으면 토스트 메시지 처리해서 못 나가게 했음.  ==> 해결
